version: '2.2'

services:
  yarn:
    image: node:alpine
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./:/scripts:rw
    working_dir: /scripts
    entrypoint: ["yarn"]
    command: ["serve:docker"]
