import { library } from '@fortawesome/fontawesome-svg-core';
import { faGithub } from '@fortawesome/free-brands-svg-icons';
import {
  faAngleDown,
  faAngleRight,
  faBars,
  faBookDead,
  faCog,
  faCogs,
  faDiceD6,
  faDiceD20,
  faExclamation,
  faExclamationCircle,
  faFireAlt,
  faLayerGroup,
  faMapMarkerAlt,
  faMinus,
  faMobile,
  faMoon,
  faPlayCircle,
  faPlus,
  faSlash,
  faSort,
  faSun,
  faUndoAlt,
  faUserPlus,
  faUsers,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faGithub,

  faAngleDown,
  faAngleRight,
  faBars,
  faBookDead,
  faCog,
  faCogs,
  faDiceD6,
  faDiceD20,
  faExclamation,
  faExclamationCircle,
  faFireAlt,
  faLayerGroup,
  faMapMarkerAlt,
  faMinus,
  faMobile,
  faMoon,
  faPlayCircle,
  faPlus,
  faSlash,
  faSort,
  faSun,
  faUndoAlt,
  faUserPlus,
  faUsers,
);
