import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAngleDown,
  faAngleRight,
  faBars,
  faBookDead,
  faCog,
  faDiceD20,
  faExclamation,
  faExclamationCircle,
  faLayerGroup,
  faMapMarkerAlt,
  faMoon,
  faPlayCircle,
  faSort,
  faSun,
  faUserPlus,
  faUsers,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faAngleDown,
  faAngleRight,
  faBars,
  faBookDead,
  faCog,
  faDiceD20,
  faExclamation,
  faExclamationCircle,
  faLayerGroup,
  faMapMarkerAlt,
  faMoon,
  faPlayCircle,
  faSort,
  faSun,
  faUserPlus,
  faUsers,
);
